// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTdBA_4w1APS2_tvUwEouO9cTSI00gFGo',
    appId: '1:449694857994:web:7f145cd68fbc6070db58f3',
    messagingSenderId: '449694857994',
    projectId: 'campus-ventures-link',
    authDomain: 'campus-ventures-link.firebaseapp.com',
    storageBucket: 'campus-ventures-link.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhzPBw8XR8pKTpJS8JvMhOqq2K4KvMUrU',
    appId: '1:449694857994:android:e71c83189b385fcfdb58f3',
    messagingSenderId: '449694857994',
    projectId: 'campus-ventures-link',
    storageBucket: 'campus-ventures-link.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbEYo5Il3zMbZinRkL0hZUt4P9Kq-QfY',
    appId: '1:449694857994:ios:4938b6afed613339db58f3',
    messagingSenderId: '449694857994',
    projectId: 'campus-ventures-link',
    storageBucket: 'campus-ventures-link.firebasestorage.app',
    iosBundleId: 'com.example.campusVenturesLink',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbEYo5Il3zMbZinRkL0hZUt4P9Kq-QfY',
    appId: '1:449694857994:ios:4938b6afed613339db58f3',
    messagingSenderId: '449694857994',
    projectId: 'campus-ventures-link',
    storageBucket: 'campus-ventures-link.firebasestorage.app',
    iosBundleId: 'com.example.campusVenturesLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTdBA_4w1APS2_tvUwEouO9cTSI00gFGo',
    appId: '1:449694857994:web:1746a345aaf8fc4fdb58f3',
    messagingSenderId: '449694857994',
    projectId: 'campus-ventures-link',
    authDomain: 'campus-ventures-link.firebaseapp.com',
    storageBucket: 'campus-ventures-link.firebasestorage.app',
  );
}
